export interface PricingPackage {
  id: string
  service: string
  name: string
  tier: 'essential' | 'premium' | 'elite'
  price: { sedan: number; suv: number; exotic?: number }
  warranty: string
  includes: string[]
  recommended: boolean
  badge?: string
}

export const PRICING_PACKAGES: PricingPackage[] = [
  {
    id: 'ceramic-essential',
    service: 'ceramic-coating',
    name: 'Ceramic Essential',
    tier: 'essential',
    price: { sedan: 1500, suv: 2000, exotic: 2800 },
    warranty: '2 Years',
    includes: [
      'Full exterior wash & decontamination',
      'Clay bar treatment',
      'Single-stage polish',
      'GYEON Mohs Ceramic Coating',
      '2-year warranty certificate',
    ],
    recommended: false,
  },
  {
    id: 'ceramic-premium',
    service: 'ceramic-coating',
    name: 'Ceramic Premium',
    tier: 'premium',
    price: { sedan: 2500, suv: 3200, exotic: 4500 },
    warranty: '5 Years',
    includes: [
      'Full exterior wash & decontamination',
      'Iron decontamination',
      'Clay bar treatment',
      'Dual-stage paint correction',
      'GYEON Mohs+ or Ceramic Pro 9H',
      'Window coating included',
      '5-year warranty certificate',
      'Free annual maintenance wash',
    ],
    recommended: true,
    badge: 'Most Popular',
  },
  {
    id: 'ceramic-elite',
    service: 'ceramic-coating',
    name: 'Ceramic Elite',
    tier: 'elite',
    price: { sedan: 4500, suv: 6000, exotic: 8500 },
    warranty: '10 Years',
    includes: [
      'Full exterior wash & decontamination',
      'Full iron & chemical decontamination',
      'Clay bar treatment',
      'Three-stage paint correction (95%+ correction)',
      'Premium top-tier ceramic coating',
      'Window coating',
      'Wheel & brake caliper coating',
      'Interior glass coating',
      '10-year warranty certificate',
      'Free annual maintenance for life of warranty',
    ],
    recommended: false,
    badge: 'Best Protection',
  },
  {
    id: 'ppf-partial',
    service: 'ppf',
    name: 'PPF Partial Front',
    tier: 'essential',
    price: { sedan: 2500, suv: 3200, exotic: 4000 },
    warranty: '10 Years Film',
    includes: [
      'Full bonnet/hood coverage',
      'Front bumper coverage',
      'Both front wings/fenders',
      'Door edge guards',
      'Mirror caps',
      'Xpel or SunTek film',
      'Computer-cut patterns',
    ],
    recommended: false,
  },
  {
    id: 'ppf-full',
    service: 'ppf',
    name: 'PPF Full Body',
    tier: 'elite',
    price: { sedan: 7500, suv: 10000, exotic: 15000 },
    warranty: '10 Years Film',
    includes: [
      'Complete full body coverage',
      'All painted surfaces protected',
      'Self-healing urethane technology',
      'Hydrophobic top coat',
      'Xpel Ultimate Plus or SunTek Ultra',
      'Computer-cut precision patterns',
      '10-year manufacturer warranty',
      'Ceramic coating over PPF included',
    ],
    recommended: true,
    badge: 'Maximum Protection',
  },
  {
    id: 'graphene-premium',
    service: 'graphene-coating',
    name: 'Graphene Premium',
    tier: 'premium',
    price: { sedan: 2800, suv: 3800, exotic: 5500 },
    warranty: '7 Years',
    includes: [
      'Full decontamination wash',
      'Iron decontamination',
      'Clay bar',
      'Dual-stage paint correction',
      'Next-gen graphene coating',
      'Anti-static protection',
      'Window graphene coating',
      '7-year warranty',
    ],
    recommended: true,
    badge: 'Recommended for Dubai',
  },
  {
    id: 'detailing-full',
    service: 'detailing',
    name: 'Full Detailing Package',
    tier: 'premium',
    price: { sedan: 650, suv: 850, exotic: 1200 },
    warranty: 'Satisfaction Guarantee',
    includes: [
      'Two-bucket exterior hand wash',
      'Clay bar decontamination',
      'Wheel & tyre deep clean',
      'Premium wax/sealant application',
      'Full interior vacuum & extraction',
      'Leather cleaning & conditioning',
      'Interior steam cleaning',
      'All glass cleaning inside & out',
      'Engine bay cleaning',
    ],
    recommended: true,
    badge: 'Best Value',
  },
  {
    id: 'window-tint-premium',
    service: 'window-tinting',
    name: 'Window Tint Premium',
    tier: 'premium',
    price: { sedan: 1200, suv: 1500, exotic: 2000 },
    warranty: 'Lifetime',
    includes: [
      'All 5 windows including windshield strip',
      'Xpel Prime XR+ nano-ceramic film',
      '99% UV rejection',
      '70% heat rejection',
      'Signal-safe technology',
      'RTA compliant VLT levels',
      'Lifetime manufacturer warranty',
    ],
    recommended: true,
    badge: 'Most Popular',
  },
]
